---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/bosh-dns-release
    tag: acceptance-tests-windows

inputs:
  - name: bosh-dns-release
  - name: candidate-release
  - name: envs
  - name: bosh-candidate-stemcell-windows
  - name: gcp-linux-stemcell

run:
  path: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.sh

params:
  ENV_NAME: default
  WINDOWS_OS_VERSION: windows2012R2
