---
groups:
- name: all
  jobs:
  - test-unit
  - test-coredns-cache
  - test-unit-windows
  - test-unit-release
  - create-release
  - test-performance
  - test-performance-windows
  - test-acceptance
  - test-acceptance-windows
  - test-acceptance-windows2016
  - test-stress
  - brats-ubuntu
  - bbl-up
  - bbl-destroy
  - finalize-release
  - bump-major

jobs:
- name: test-unit
  public: true
  plan:
    - get: bosh-dns-release
      trigger: true
    - task: test-unit
      file: bosh-dns-release/ci/tasks/test-unit.yml

- name: test-coredns-cache
  public: true
  plan:
    - get: coredns
      trigger: true
    - get: bosh-dns-release
    - task: test-cache
      file: bosh-dns-release/ci/tasks/test-cache.yml

- name: test-unit-windows
  public: true
  serial: true
  plan:
    - get: bosh-dns-release
      trigger: true
    - task: test-unit-windows
      timeout: 1h
      file: bosh-dns-release/ci/tasks/windows/test-unit-windows.yml

- name: test-unit-release
  public: true
  plan:
    - get: bosh-dns-release
      trigger: true
    - task: test-unit-release
      file: bosh-dns-release/ci/tasks/test-unit-release.yml

- name: create-release
  plan:
    - get: bosh-dns-release
      trigger: true
      passed:
      - test-unit
      - test-unit-windows
      - test-unit-release
    - task: create
      file: bosh-dns-release/ci/tasks/create-candidate.yml
    - put: candidate-release
      params:
        file: "release/bosh-dns-dev-release.tgz"

- name: test-performance
  interruptible: true
  public: true
  serial: true
  plan:
    - get: every-10m
      trigger: true
    - get: bosh-dns-release
      trigger: true
      passed: [create-release]
    - task: test-performance
      tags: ["dns-performance"]
      privileged: true
      file: bosh-dns-release/ci/tasks/test-performance.yml
      params:
        ZONES_JSON_HASH: {{zones_json_hash}}
        DATADOG_API_KEY: {{datadog_api_key}}
        DATADOG_ENVIRONMENT_TAG: bosh-dns-ci-linux

- name: test-performance-windows
  interruptible: true
  public: true
  serial: true
  plan:
    - get: every-10m
      trigger: true
    - get: bosh-dns-release
      trigger: true
      passed: [create-release]
    - task: test-performance
      file: bosh-dns-release/ci/tasks/windows/test-performance-windows.yml
      timeout: 1h
      params:
        ZONES_JSON_HASH: {{zones_json_hash}}
        DATADOG_API_KEY: {{datadog_api_key}}
        DATADOG_ENVIRONMENT_TAG: bosh-dns-ci-windows

- name: test-acceptance
  public: true
  serial: true
  plan:
    - aggregate:
      - get: bosh-dns-release
        passed: [create-release]
      - get: bosh-candidate-stemcell
      - get: bosh-candidate-release
      - get: candidate-release
        trigger: true
        passed: [create-release]
    - task: test-acceptance
      privileged: true
      file: bosh-dns-release/ci/tasks/test-acceptance.yml

- name: test-acceptance-windows
  public: true
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
  - ensure:
      task: clean-up
      file: bosh-dns-release/ci/tasks/clean-up.yml
    do:
    - aggregate:
      - get: bosh-dns-release
        trigger: true
        passed: [create-release]
      - get: envs
      - get: bosh-deployment
      - get: gcp-linux-stemcell
      - get: bosh-candidate-stemcell-windows
      - get: bosh-candidate-release
      - get: candidate-release
        trigger: true
        passed: [create-release]
    - task: windows
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows.yml
      params:
        WINDOWS_OS_VERSION: windows2012R2
      timeout: 1h
    - task: windows-nameserver-disabled
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.yml
      timeout: 1h
    - task: windows-shared
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.yml
      timeout: 1h

- name: test-acceptance-windows2016
  public: true
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
  - do:
    - aggregate:
      - get: bosh-dns-release
        passed:
        - create-release
        trigger: true
      - get: envs
      - get: bosh-deployment
      - get: gcp-linux-stemcell
      - get: bosh-candidate-stemcell-windows2016
      - get: bosh-candidate-release
      - get: candidate-release
        passed:
        - create-release
        trigger: true
    - task: windows
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows.yml
      params:
        WINDOWS_OS_VERSION: windows2016
      input_mapping:
        bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
      timeout: 1h
    - task: windows-nameserver-disabled
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-nameserver-disabled.yml
      params:
        WINDOWS_OS_VERSION: windows2016
      input_mapping:
        bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
      timeout: 1h
    - task: windows-shared
      file: bosh-dns-release/ci/tasks/windows/test-acceptance-windows-shared.yml
      params:
        WINDOWS_OS_VERSION: windows2016
      input_mapping:
        bosh-candidate-stemcell-windows: bosh-candidate-stemcell-windows2016
      timeout: 1h
    ensure:
      task: clean-up
      file: bosh-dns-release/ci/tasks/clean-up.yml

- name: test-stress
  public: false
  serial: true
  plan:
    - aggregate:
      - get: bosh-dns-release
        trigger: true
        passed: [create-release]
      - get: bbl-state
        resource: envs
      - get: bosh-deployment
      - get: docker-release
      - get: stemcell
      - get: warden-stemcell
      - get: bosh-docker-cpi-release
        resource: bosh-docker-cpi-release-git
    - do:
      - task: setup-env
        file: bosh-dns-release/ci/tasks/test-stress/setup-env.yml
        params:
          BBL_AWS_ACCESS_KEY_ID: {{bbl_test_stress_access_key_id}}
          BBL_AWS_SECRET_ACCESS_KEY: {{bbl_test_stress_secret_access_key}}
          BBL_AWS_REGION: us-west-2
          BBL_IAAS: aws
          BBL_STATE_DIR: test-stress/bbl-state
        ensure:
          put: envs
          params:
            repository: updated-bbl-state
      - task: deploy-docker-vms
        file: bosh-dns-release/ci/tasks/test-stress/deploy-docker.yml
        input_mapping:
          bbl-state: updated-bbl-state
      - task: deploy-containers
        file: bosh-dns-release/ci/tasks/test-stress/deploy-n.yml
        input_mapping:
          stemcell: warden-stemcell
          bbl-state: updated-bbl-state
      - task: stress-containers
        file: bosh-dns-release/ci/tasks/test-stress/run-errand.yml
        input_mapping:
          bbl-state: updated-bbl-state
      ensure:
        task: destroy-env
        file: bosh-dns-release/ci/tasks/test-stress/destroy-env.yml
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_AWS_ACCESS_KEY_ID: {{bbl_test_stress_access_key_id}}
          BBL_AWS_SECRET_ACCESS_KEY: {{bbl_test_stress_secret_access_key}}
          BBL_STATE_DIR: test-stress/bbl-state
        ensure:
          put: envs
          params:
            repository: bbl-state

- name: brats-ubuntu
  serial: true
  plan:
  - do:
    - aggregate:
      - get: brats-src
      - get: bosh-dns-release
        resource: candidate-release
        trigger: true
        passed: [create-release]
      - get: stemcell
        resource: bosh-candidate-stemcell
      - get: bosh-release
    - task: test-brats # contain base manifest
      file: brats-src/ci/tasks/test-brats.yml
      tags: ["worker-brats"]
      privileged: true
      input_mapping:
        dns-release: bosh-dns-release-src
        bosh-src: brats-src
      params:
        BOSH_DIRECTOR_RELEASE_PATH: "bosh-release/release.tgz"
        BOSH_DIRECTOR_RELEASE_VERSION: "latest"
        DNS_RELEASE_FILE_PATH: "dns-release"
        DNS_RELEASE_VERSION: "create"

- name: bbl-up
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: bosh-dns-release
    - get: bosh-deployment
    - get: bosh-candidate-release
    - get: envs
    - task: bbl-up
      file: bosh-dns-release/ci/tasks/bbl-up.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: envs

- name: bbl-destroy
  serial: true
  serial_groups:
  - windows-acceptance-env
  plan:
    - get: bosh-dns-release
    - get: env-repo
      resource: envs
    - task: bbl-destroy
      file: bosh-dns-release/ci/tasks/bbl-destroy.yml
      params:
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key_id}}
      ensure:
        put: envs
        params:
          repository: updated-env-repo

- name: finalize-release
  serial_groups:
    - version
  plan:
    - aggregate:
      - get: bosh-dns-release
        passed: [test-acceptance, test-acceptance-windows, test-stress]
      - get: candidate-release
        passed: [test-acceptance, brats-ubuntu, test-acceptance-windows]
      - get: version
    - task: finalize-release
      file: bosh-dns-release/ci/tasks/finalize-release.yml
      params:
        BLOBSTORE_ACCESS_KEY_ID: {{release_blobs_access_key_id}}
        BLOBSTORE_SECRET_ACCESS_KEY: {{release_blobs_secret_access_key}}
    - put: version
      params:
        bump: minor
    - put: bosh-dns-release
      params:
        rebase: true
        repository: final-bosh-dns-release

- name: bump-major
  serial_groups:
    - version
  plan:
    - put: version
      params:
        bump: major

resources:
- name: bosh-dns-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-dns-release
    branch: new-test-stress
    private_key: {{github_deployment_key}}
    ignore_paths:
    - ci/docker

- name: coredns
  type: git
  source:
    uri: https://github.com/bosh-dep-forks/coredns.git
    branch: bosh-develop

- name: version
  type: semver
  source:
    bucket: {{candidate_release_bucket}}
    key: version
    access_key_id: {{candidate_release_access_key_id}}
    secret_access_key: {{candidate_release_secret_access_key}}

- name: candidate-release
  type: s3
  source:
    bucket: {{candidate_release_bucket}}
    access_key_id: {{candidate_release_access_key_id}}
    secret_access_key: {{candidate_release_secret_access_key}}
    versioned_file: "bosh-dns-dev-release.tgz"

- name: brats-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh
    branch: 264.x

- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: bosh-docker-cpi-release-git
  type: git
  source:
    uri: https://github.com/cppforlife/bosh-docker-cpi-release
    branch: master

- name: docker-release
  type: bosh-io-release
  source:
    repository: cppforlife/docker-release

- name: bosh-candidate-stemcell
  type: s3
  source:
    bucket: bosh-core-stemcells-candidate
    regexp: warden/bosh-stemcell-(.+)-warden-boshlite-ubuntu-trusty-go_agent.tgz

- name: bosh-candidate-stemcell-windows
  type: s3
  source:
    region_name: us-east-2
    bucket: bosh-windows-stemcells-production
    regexp: light-bosh-stemcell-(.+)-google-kvm-windows2012R2-go_agent.tgz

- name: bosh-candidate-stemcell-windows2016
  type: s3
  source:
    bucket: bosh-windows-stemcells-production
    regexp: 1709/light-bosh-stemcell-(.+)-google-kvm-windows2016-go_agent.tgz
    region_name: us-east-2

- name: bosh-candidate-release
  type: s3
  source:
    bucket: bosh-candidate-release-tarballs
    versioned_file: bosh-dev-release.tgz

- name: gcp-linux-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dns-release-ci-envs.git
    private_key: {{envs_private_key}}

- name: every-10m
  type: time
  source: {interval: 10m}

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: warden-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
