---
groups:
- name: all
  jobs:
  - test-stress

jobs:
- name: test-stress
  public: false
  serial: true
  serial_groups:
  - test-stress-group
  plan:
    - aggregate:
      - get: bbl-state
        resource: envs
      - get: bosh-deployment
      - get: bosh-dns-release
      - get: bosh-docker-cpi-release
      - get: stemcell
      - get: warden-stemcell
      - get: cf-deployment-concourse-tasks
      - get: env-repo
        resource: envs
      - get: ops-files
        resource: envs
    - task: pre-clean
      file: bosh-dns-release/ci/tasks/test-stress/clean-up.yml
    - do:
      - task: deploy-to-aws
        file: bosh-dns-release/ci/tasks/test-stress/deploy-inner-bosh.yml
      - task: deploy-containers
        file: bosh-dns-release/ci/tasks/test-stress/deploy-n.yml
        input_mapping:
          stemcell: warden-stemcell
      - task: stress-containers
        file: bosh-dns-release/ci/tasks/test-stress/run-errand.yml
      ensure:
        task: post-clean
        file: bosh-dns-release/ci/tasks/test-stress/clean-up.yml

resources:
- name: envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dns-release-ci-envs.git
    private_key: {{envs_private_key}}

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/jrussett/bosh-deployment
    branch: test-stress-pipeline

- name: bosh-dns-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-dns-release
    branch: test-stress-pipeline
    private_key: {{github_deployment_key}}
    ignore_paths:
    - ci/docker

- name: bosh-docker-cpi-release
  type: git
  source:
    uri: https://github.com/cppforlife/bosh-docker-cpi-release
    branch: master

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version_family: "3468.latest"

- name: warden-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version_family: "3468.latest"

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: fix-aws-lb
    uri: https://github.com/bosh-dep-forks/cf-deployment-concourse-tasks
