---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v4

inputs:
  - name: bbl-state
  - name: bosh-dns-release
  - name: inner-bosh-vars
  - name: stemcell

outputs: []

params:
  DEPLOYMENTS_OF_100: 10
  PARALLEL_DEPLOYMENTS: 5
  BBL_STATE_SUBDIRECTORY: test-stress/bbl-state

run:
  path: bosh-dns-release/ci/tasks/test-stress/deploy-n.sh
